//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Petrovich.Business.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Petrovich.Business.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error. Check inner exception for details..
        /// </summary>
        internal static string E0 {
            get {
                return ResourceManager.GetString("E0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while fetching data from database repository. Check inner exception for details..
        /// </summary>
        internal static string E1 {
            get {
                return ResourceManager.GetString("E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated branch inventory part &apos;{0}&apos; found on item with id: &apos;{1}&apos;..
        /// </summary>
        internal static string E400001 {
            get {
                return ResourceManager.GetString("E400001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch inventory part could not be changed for item with id: &apos;{0}&apos;..
        /// </summary>
        internal static string E400002 {
            get {
                return ResourceManager.GetString("E400002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product inventory part could not be changed for item with id: &apos;{0}&apos;..
        /// </summary>
        internal static string E400003 {
            get {
                return ResourceManager.GetString("E400003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no available slots for new categories in branch &apos;{0}&apos;..
        /// </summary>
        internal static string E400004 {
            get {
                return ResourceManager.GetString("E400004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category inventory part could not be changed for item with id: &apos;{0}&apos;..
        /// </summary>
        internal static string E400005 {
            get {
                return ResourceManager.GetString("E400005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child categories exists for branch &apos;{0}&apos;..
        /// </summary>
        internal static string E400006 {
            get {
                return ResourceManager.GetString("E400006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child groups exists for category &apos;{0}&apos;..
        /// </summary>
        internal static string E400007 {
            get {
                return ResourceManager.GetString("E400007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no available slots for new products in category &apos;{0}&apos;..
        /// </summary>
        internal static string E400008 {
            get {
                return ResourceManager.GetString("E400008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child products exists for branch &apos;{0}&apos;..
        /// </summary>
        internal static string E400009 {
            get {
                return ResourceManager.GetString("E400009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image format is not supported for file &apos;{0}&apos;..
        /// </summary>
        internal static string E400010 {
            get {
                return ResourceManager.GetString("E400010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group inventory part could not be changed for item with id: &apos;{0}&apos;..
        /// </summary>
        internal static string E400011 {
            get {
                return ResourceManager.GetString("E400011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no available slots for new groups in category &apos;{0}&apos;..
        /// </summary>
        internal static string E400012 {
            get {
                return ResourceManager.GetString("E400012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no available slots for new products in group &apos;{0}&apos;..
        /// </summary>
        internal static string E400013 {
            get {
                return ResourceManager.GetString("E400013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log entity &apos;{0}&apos; not found..
        /// </summary>
        internal static string E404001 {
            get {
                return ResourceManager.GetString("E404001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; not found..
        /// </summary>
        internal static string E404002 {
            get {
                return ResourceManager.GetString("E404002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch &apos;{0}&apos; not found..
        /// </summary>
        internal static string E404003 {
            get {
                return ResourceManager.GetString("E404003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category &apos;{0}&apos; not found..
        /// </summary>
        internal static string E404004 {
            get {
                return ResourceManager.GetString("E404004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group &apos;{0}&apos; not found..
        /// </summary>
        internal static string E404005 {
            get {
                return ResourceManager.GetString("E404005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product &apos;{0}&apos; not found..
        /// </summary>
        internal static string E404006 {
            get {
                return ResourceManager.GetString("E404006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image &apos;{0}&apos; not found..
        /// </summary>
        internal static string E404007 {
            get {
                return ResourceManager.GetString("E404007", resourceCulture);
            }
        }
    }
}
